// Complete list of vehicle makes available in the US market
export const VEHICLE_MAKES = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lucid",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Polestar",
  "Porsche",
  "Ram",
  "Rivian",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
  // Less common but still present
  "Fisker",
  "Lotus",
  "Maybach",
  "Pontiac",
  "Saturn",
  "Scion",
  "Smart",
  "Suzuki",
  "Hummer",
  "Oldsmobile",
  "Mercury",
  "Plymouth",
  "Saab",
  "Other",
];

// Common models by make (subset for autocomplete suggestions)
export const POPULAR_MODELS = {
  Toyota: [
    "Camry",
    "Corolla",
    "RAV4",
    "Highlander",
    "Tacoma",
    "Prius",
    "4Runner",
    "Tundra",
    "Sienna",
  ],
  Honda: [
    "Civic",
    "Accord",
    "CR-V",
    "Pilot",
    "Odyssey",
    "HR-V",
    "Ridgeline",
    "Passport",
  ],
  Ford: [
    "F-150",
    "Mustang",
    "Explorer",
    "Escape",
    "Edge",
    "Bronco",
    "Ranger",
    "Expedition",
    "Fusion",
  ],
  Chevrolet: [
    "Silverado",
    "Equinox",
    "Tahoe",
    "Malibu",
    "Traverse",
    "Colorado",
    "Camaro",
    "Suburban",
  ],
  Nissan: [
    "Altima",
    "Rogue",
    "Sentra",
    "Pathfinder",
    "Murano",
    "Frontier",
    "Maxima",
    "Titan",
  ],
  Hyundai: [
    "Elantra",
    "Sonata",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Kona",
    "Ioniq",
  ],
  Kia: [
    "Optima",
    "Sorento",
    "Sportage",
    "Telluride",
    "Soul",
    "Forte",
    "Seltos",
  ],
  BMW: ["3 Series", "5 Series", "X3", "X5", "X1", "7 Series", "X7", "M3", "M5"],
  "Mercedes-Benz": [
    "C-Class",
    "E-Class",
    "S-Class",
    "GLC",
    "GLE",
    "A-Class",
    "GLA",
    "AMG GT",
  ],
  Audi: ["A4", "A6", "Q5", "Q7", "A3", "Q3", "e-tron", "RS"],
  Lexus: ["RX", "ES", "NX", "IS", "GX", "LX", "LS", "UX"],
  Jeep: [
    "Wrangler",
    "Grand Cherokee",
    "Cherokee",
    "Compass",
    "Gladiator",
    "Renegade",
  ],
  Subaru: [
    "Outback",
    "Forester",
    "Crosstrek",
    "Impreza",
    "Legacy",
    "Ascent",
    "WRX",
  ],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Volkswagen: ["Jetta", "Passat", "Tiguan", "Atlas", "Golf", "ID.4", "Taos"],
  Mazda: ["CX-5", "Mazda3", "CX-9", "CX-30", "Mazda6", "MX-5 Miata"],
  GMC: ["Sierra", "Yukon", "Acadia", "Terrain", "Canyon", "Hummer EV"],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  Dodge: ["Charger", "Challenger", "Durango", "Grand Caravan", "Journey"],
  Buick: ["Enclave", "Encore", "Envision", "LaCrosse", "Regal"],
  Cadillac: ["Escalade", "XT5", "XT4", "CT5", "CT4", "Lyriq"],
  Lincoln: ["Navigator", "Aviator", "Nautilus", "Corsair", "Continental"],
  Acura: ["MDX", "RDX", "TLX", "ILX", "NSX", "Integra"],
  Infiniti: ["QX60", "QX80", "Q50", "QX50", "QX55"],
  Volvo: ["XC90", "XC60", "XC40", "S60", "S90", "V60"],
  Porsche: [
    "911",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
    "Boxster",
    "Cayman",
  ],
  "Land Rover": [
    "Range Rover",
    "Range Rover Sport",
    "Discovery",
    "Defender",
    "Evoque",
  ],
  Jaguar: ["F-Pace", "E-Pace", "XF", "XE", "F-Type", "I-Pace"],
  Mitsubishi: ["Outlander", "Eclipse Cross", "Outlander Sport", "Mirage"],
  Mini: ["Cooper", "Countryman", "Clubman"],
};

export default VEHICLE_MAKES;
